-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`RATER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RATER` (
  `RATER_USERNAME` VARCHAR(45) NOT NULL,
  `RATER_PASSWORD` VARCHAR(45) NOT NULL,
  `RATER_PROFILE_PICTURE` LONGBLOB NULL,
  `RATER_DOB` DATE NULL,
  `RATER_EMAIL_ADDRESS` VARCHAR(45) NOT NULL,
  `RATER_AREA_CODE` CHAR(3) NULL,
  `RATER_PHONE_NUMBER` CHAR(7) NULL,
  UNIQUE INDEX `RATER_USERNAME_UNIQUE` (`RATER_USERNAME` ASC) VISIBLE,
  PRIMARY KEY (`RATER_USERNAME`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RATEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RATEE` (
  `RATEE_ID` INT(12) UNSIGNED NOT NULL AUTO_INCREMENT,
  `RATEE_OVERALL_SCORE` DECIMAL(4,2) NOT NULL,
  `RATEE_PERSONAL_PICTURE` LONGBLOB NOT NULL,
  `RATEE_FIRSTNAME` VARCHAR(45) NOT NULL,
  `RATEE_LASTNAME` VARCHAR(45) NOT NULL,
  `RATEE_STATE` CHAR(2) NOT NULL,
  `RATEE_BIRTHYEAR` CHAR(4) NOT NULL,
  PRIMARY KEY (`RATEE_ID`),
  UNIQUE INDEX `RATEE_ID_UNIQUE` (`RATEE_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PERSONALITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PERSONALITY` (
  `PERSONALITY_ID` INT(12) NOT NULL AUTO_INCREMENT,
  `PERSONALITY_OVERALL_SCORE` DECIMAL(4,2) NOT NULL,
  `PERSONALITY_HONESTY_SCORE` INT(2) NOT NULL,
  `PERSONALITY_EMPATHY_SCORE` INT(2) NOT NULL,
  `PERSONALITY_MATURITY_SCORE` INT(2) NOT NULL,
  `PERSONALITY_SENSE_OF_HUMOR_SCORE` INT(2) NOT NULL,
  `PERSONALITY_AFFECTION_SCORE` INT(2) NOT NULL,
  `RATEE_RATEE_ID` INT(12) UNSIGNED NOT NULL,
  PRIMARY KEY (`PERSONALITY_ID`, `RATEE_RATEE_ID`),
  UNIQUE INDEX `PERSONALITY_ID_UNIQUE` (`PERSONALITY_ID` ASC) VISIBLE,
  INDEX `fk_PERSONALITY_RATEE1_idx` (`RATEE_RATEE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PERSONALITY_RATEE1`
    FOREIGN KEY (`RATEE_RATEE_ID`)
    REFERENCES `mydb`.`RATEE` (`RATEE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOOKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOOKS` (
  `LOOKS_ID` INT(12) NOT NULL AUTO_INCREMENT,
  `LOOKS_OVERALL_SCORE` DECIMAL(4,2) NOT NULL,
  `LOOKS_HYGIENE_SCORE` INT(2) NOT NULL,
  `LOOKS_DRESS_APPEARANCE_SCORE` INT(2) NOT NULL,
  `RATEE_RATEE_ID` INT(12) UNSIGNED NOT NULL,
  PRIMARY KEY (`LOOKS_ID`, `RATEE_RATEE_ID`),
  UNIQUE INDEX `LOOKS_ID_UNIQUE` (`LOOKS_ID` ASC) VISIBLE,
  INDEX `fk_LOOKS_RATEE1_idx` (`RATEE_RATEE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_LOOKS_RATEE1`
    FOREIGN KEY (`RATEE_RATEE_ID`)
    REFERENCES `mydb`.`RATEE` (`RATEE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAREER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAREER` (
  `CAREER_ID` INT(12) NOT NULL AUTO_INCREMENT,
  `CAREER_OVERALL_SCORE` DECIMAL(4,2) NOT NULL,
  `CAREER_JOB_SATISFACTION_SCORE` INT(2) NOT NULL,
  `CAREER_INCOME_SCORE` INT(2) NOT NULL,
  `RATEE_RATEE_ID` INT(12) UNSIGNED NOT NULL,
  PRIMARY KEY (`CAREER_ID`, `RATEE_RATEE_ID`),
  UNIQUE INDEX `CAREER_ID_UNIQUE` (`CAREER_ID` ASC) VISIBLE,
  INDEX `fk_CAREER_RATEE1_idx` (`RATEE_RATEE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CAREER_RATEE1`
    FOREIGN KEY (`RATEE_RATEE_ID`)
    REFERENCES `mydb`.`RATEE` (`RATEE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CRIMINAL_RECORD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CRIMINAL_RECORD` (
  `CRIMINAL_RECORD_ID` INT(12) NOT NULL AUTO_INCREMENT,
  `CRIMINAL_RECORD_STATUS` TINYINT(1) NULL,
  `RATEE_RATEE_ID` INT(12) UNSIGNED NOT NULL,
  PRIMARY KEY (`CRIMINAL_RECORD_ID`, `RATEE_RATEE_ID`),
  UNIQUE INDEX `CRIMINAL_RECORD_ID_UNIQUE` (`CRIMINAL_RECORD_ID` ASC) VISIBLE,
  INDEX `fk_CRIMINAL_RECORD_RATEE1_idx` (`RATEE_RATEE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CRIMINAL_RECORD_RATEE1`
    FOREIGN KEY (`RATEE_RATEE_ID`)
    REFERENCES `mydb`.`RATEE` (`RATEE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMINISTRATOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMINISTRATOR` (
  `ADMINISTRATOR_USERNAME` VARCHAR(45) NOT NULL,
  `ADMINISTRATOR_PASSWORD` VARCHAR(45) NOT NULL,
  `ADMINISTRATOR_EMAIL_ADDRESS` VARCHAR(45) NOT NULL,
  `ADMINISTRATOR_AREA_CODE` CHAR(3) NULL,
  `ADMINISTRATOR_PHONE_NUMBER` CHAR(7) NULL,
  `ADMINISTRATOR_PROFILE_PICTURE` LONGBLOB NULL,
  PRIMARY KEY (`ADMINISTRATOR_USERNAME`),
  UNIQUE INDEX `ADMINISTRATOR_USERNAME_UNIQUE` (`ADMINISTRATOR_USERNAME` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMMENTS` (
  `COMMENTS_ID` INT(12) NOT NULL AUTO_INCREMENT,
  `COMMENTS_DATE` DATETIME NOT NULL,
  `COMMENTS_TEXT` LONGTEXT NOT NULL,
  `RATEE_RATEE_ID` INT(12) UNSIGNED NOT NULL,
  `RATER_RATER_USERNAME` VARCHAR(45) NULL,
  `ADMINISTRATOR_ADMINISTRATOR_USERNAME` VARCHAR(45) NULL,
  PRIMARY KEY (`COMMENTS_ID`, `RATEE_RATEE_ID`),
  UNIQUE INDEX `COMMENT_ID_UNIQUE` (`COMMENTS_ID` ASC) VISIBLE,
  INDEX `fk_COMMENT_RATEE1_idx` (`RATEE_RATEE_ID` ASC) VISIBLE,
  INDEX `fk_COMMENT_RATER1_idx` (`RATER_RATER_USERNAME` ASC) VISIBLE,
  INDEX `fk_COMMENT_ADMINISTRATOR1_idx` (`ADMINISTRATOR_ADMINISTRATOR_USERNAME` ASC) VISIBLE,
  CONSTRAINT `fk_COMMENT_RATEE1`
    FOREIGN KEY (`RATEE_RATEE_ID`)
    REFERENCES `mydb`.`RATEE` (`RATEE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMENT_RATER1`
    FOREIGN KEY (`RATER_RATER_USERNAME`)
    REFERENCES `mydb`.`RATER` (`RATER_USERNAME`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMENT_ADMINISTRATOR1`
    FOREIGN KEY (`ADMINISTRATOR_ADMINISTRATOR_USERNAME`)
    REFERENCES `mydb`.`ADMINISTRATOR` (`ADMINISTRATOR_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RATER_EVALUATES_RATEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RATER_EVALUATES_RATEE` (
  `RATEE_RATEE_ID` INT(12) UNSIGNED NOT NULL,
  `RATER_RATER_USERNAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RATEE_RATEE_ID`, `RATER_RATER_USERNAME`),
  INDEX `fk_RATER_evaluates_RATEE_RATEE1_idx` (`RATEE_RATEE_ID` ASC) VISIBLE,
  UNIQUE INDEX `RATEE_RATEE_ID_UNIQUE` (`RATEE_RATEE_ID` ASC) VISIBLE,
  INDEX `fk_RATER_EVALUATES_RATEE_RATER1_idx` (`RATER_RATER_USERNAME` ASC) VISIBLE,
  UNIQUE INDEX `RATER_RATER_USERNAME_UNIQUE` (`RATER_RATER_USERNAME` ASC) VISIBLE,
  CONSTRAINT `fk_RATER_evaluates_RATEE_RATEE1`
    FOREIGN KEY (`RATEE_RATEE_ID`)
    REFERENCES `mydb`.`RATEE` (`RATEE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RATER_EVALUATES_RATEE_RATER1`
    FOREIGN KEY (`RATER_RATER_USERNAME`)
    REFERENCES `mydb`.`RATER` (`RATER_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMINISTRATOR_MODERATES_RATER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMINISTRATOR_MODERATES_RATER` (
  `ADMINISTRATOR_ADMINISTRATOR_USERNAME` VARCHAR(45) NOT NULL,
  `RATER_RATER_USERNAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ADMINISTRATOR_ADMINISTRATOR_USERNAME`, `RATER_RATER_USERNAME`),
  INDEX `fk_ADMINISTRATOR_MODERATES_RATER_ADMINISTRATOR1_idx` (`ADMINISTRATOR_ADMINISTRATOR_USERNAME` ASC) VISIBLE,
  INDEX `fk_ADMINISTRATOR_MODERATES_RATER_RATER1_idx` (`RATER_RATER_USERNAME` ASC) VISIBLE,
  UNIQUE INDEX `ADMINISTRATOR_ADMINISTRATOR_USERNAME_UNIQUE` (`ADMINISTRATOR_ADMINISTRATOR_USERNAME` ASC) VISIBLE,
  UNIQUE INDEX `RATER_RATER_USERNAME_UNIQUE` (`RATER_RATER_USERNAME` ASC) VISIBLE,
  CONSTRAINT `fk_ADMINISTRATOR_MODERATES_RATER_ADMINISTRATOR1`
    FOREIGN KEY (`ADMINISTRATOR_ADMINISTRATOR_USERNAME`)
    REFERENCES `mydb`.`ADMINISTRATOR` (`ADMINISTRATOR_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADMINISTRATOR_MODERATES_RATER_RATER1`
    FOREIGN KEY (`RATER_RATER_USERNAME`)
    REFERENCES `mydb`.`RATER` (`RATER_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMINISTRATOR_MODERATES_RATEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMINISTRATOR_MODERATES_RATEE` (
  `RATEE_RATEE_ID` INT(12) UNSIGNED NOT NULL,
  `ADMINISTRATOR_ADMINISTRATOR_USERNAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RATEE_RATEE_ID`, `ADMINISTRATOR_ADMINISTRATOR_USERNAME`),
  INDEX `fk_ADMINISTRATOR_MODERATES_RATEE_RATEE1_idx` (`RATEE_RATEE_ID` ASC) VISIBLE,
  UNIQUE INDEX `RATEE_RATEE_ID_UNIQUE` (`RATEE_RATEE_ID` ASC) VISIBLE,
  INDEX `fk_ADMINISTRATOR_MODERATES_RATEE_ADMINISTRATOR1_idx` (`ADMINISTRATOR_ADMINISTRATOR_USERNAME` ASC) VISIBLE,
  UNIQUE INDEX `ADMINISTRATOR_ADMINISTRATOR_USERNAME_UNIQUE` (`ADMINISTRATOR_ADMINISTRATOR_USERNAME` ASC) VISIBLE,
  CONSTRAINT `fk_ADMINISTRATOR_MODERATES_RATEE_RATEE1`
    FOREIGN KEY (`RATEE_RATEE_ID`)
    REFERENCES `mydb`.`RATEE` (`RATEE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ADMINISTRATOR_MODERATES_RATEE_ADMINISTRATOR1`
    FOREIGN KEY (`ADMINISTRATOR_ADMINISTRATOR_USERNAME`)
    REFERENCES `mydb`.`ADMINISTRATOR` (`ADMINISTRATOR_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
